### ISSUE TITLE
CI 存在问题

### ISSUE THREAD

**Issue by FrogDar** [FrogDar/code-contributing-practice#38]
git message 的帮助网址没有成功替换
对于 PR 中是否包含 `close` 还需要进一步的检验

**Comment by FrogDar** [comment]
![image](https://user-images.githubusercontent.com/20886330/224662237-1c0cb173-44ce-4071-a45b-8f69ebcff56d.png)

**Comment by FrogDar** [comment]
@charlie0129  为啥这样用不了

**Comment by charlie0129** [comment]
什么用不了

**Comment by FrogDar** [comment]
wocao 我是傻逼……

**Comment by FrogDar** [comment]
![image](https://user-images.githubusercontent.com/20886330/224916327-b8b022bc-7fcb-421d-869b-6372c631c870.png)

这个body里面没有获得到内容，是不是需要给权限的？

**Comment by charlie0129** [comment]
不知道的呀，感觉不要吧

**Comment by FrogDar** [comment]
> ![image](https://user-images.githubusercontent.com/20886330/224662237-1c0cb173-44ce-4071-a45b-8f69ebcff56d.png)

你看这里，获取到的就是空白      也有可能是我 点点点 错了

**Comment by charlie0129** [comment]
你那个变量里面真的有body吗
