### ISSUE TITLE
Issue 没有自动 assign 到用户

### ISSUE THREAD

**Issue by charlie0129** [FrogDar/code-contributing-practice#42]
某个 user （间接）创建的 issue 应该要 assign 给他

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/55270174/224681182-4ac61dae-ea0f-4189-93a0-1ddc94bccf1f.png">

**Comment by FrogDar** [comment]
可能是权限的问题？如果是我自己创建的，他能够 assign 到我，但是对于不在这个仓库的人，就分配不了。

**Comment by charlie0129** [comment]
不应该吧，你写了这部分的逻辑了吗？

**Comment by FrogDar** [comment]
之前试了不少呢

![image](https://user-images.githubusercontent.com/20886330/224683973-6b904a6c-3529-4fef-99ba-a56525383c3b.png)

**Comment by FrogDar** [comment]
如果我在token的区域富裕更高的权限有机会解决这个问题嘛？ 我觉得是我默认的token权限太低了？

**Comment by FrogDar** [comment]
不对 默认情况下，这个“token” 调用的该不会是 输入这个评论 1 的那个人的 token 吧？ 感觉应该类似于 “trigger” 那样子 额外调用一个东西 就和当时 分离 pull request 和 azure static web apps 那样的操作？

**Comment by charlie0129** [comment]
assign 给外面的人这个操作肯定是可以实现的。给我的感觉是你没给 bot 足够的权限

**Comment by charlie0129** [comment]
我好像没看到你有给额外权限的代码

**Comment by FrogDar** [comment]
> 我好像没看到你有给额外权限的代码

确实   我确实没有额外给

**Comment by charlie0129** [comment]
要给 issue 的 write 权限

**Comment by FrogDar** [comment]
你会发现在分配的时候，只能分配给这个仓库里的人，哪怕是手动操作

**Comment by charlie0129** [comment]
Resolution: https://github.com/FrogDar/code-contributing-practice/issues/45#issuecomment-1465995576

> 1. 创建新 issue
> 2. 以某种方式说明要完成的题目
> 3. bot 解析内容
> 4. 根据要完成的题目更新 issue 内容为题目内容并 assign

**Comment by charlie0129** [comment]
Are you working on it? @FrogDar

**Comment by FrogDar** [comment]
> Are you working on it? @FrogDar

没有  交给你干吧 怎么样？

**Comment by charlie0129** [comment]
你的仓库你修的
