### ISSUE TITLE
ex1

### ISSUE THREAD

**Issue by Gmorning730** [FrogDar/code-contributing-practice#76]
should I... create a issues there?

**Comment by FrogDar** [comment]
练习一：认领 issue 完成第一次 PR

提交一个以自己的用户名命名的 `.md` 文件，内容随意。

请注意查看 [`CONTRIBUTING.md`](https://github.com/FrogDar/code-contributing-practice/blob/main/CONTRIBUTING.md) 里的规范（比如 git message 要使用 [`angular` 规范](https://github.com/angular/angular/blob/main/CONTRIBUTING.md)）

建议自己创建一个分支，并在分支上修改后提交 PR，具体做法和理由见练习二。
